# config/packages/security.yaml
security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Usuario
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider

            # 🔥 AÑADE ESTO: Configura el autenticador JSON
            json_login:
                check_path: api_login # Coincide con el name de tu ruta en el controlador
                username_path: username
                password_path: password
            
            logout:
                path: app_logout
                target: app_login_screen

    access_control:
        # Aquí puedes añadir reglas de acceso en el futuro